version: '2.4'

services:
  api:
    container_name: vinttem_api
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
        uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
      "
    # ports:
    #   - "8000:8000"
    expose:
      - 8000
    env_file:
      - ./.env
    volumes:
      - .:/api

  proxy:
    container_name: nginx_proxy
    build:
      context: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - proxy-dhparams:/vol/proxy
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt
    env_file:
      - ./.env
    environment:
      - DOMAIN=${DOMAIN}
    depends_on:
      - api

  certbot:
    container_name: certbot
    build:
      context: ./proxy/certbot
    command: echo "Skipping..."
    env_file:
      - ./.env
    environment:
      - ACME_DEFAULT_EMAIL=${ACME_DEFAULT_EMAIL}
      - DOMAIN=${DOMAIN}
    volumes:
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt
    depends_on:
      - proxy

volumes:
  proxy-dhparams:
  certbot-web:
  certbot-certs:
