"""Initial Migration

Revision ID: 9740608f4c41
Revises: 
Create Date: 2023-06-05 20:08:13.471953

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9740608f4c41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('category', sa.Enum('recreation', 'market_stuff', 'health', 'study', 'cloths', 'housing', 'transport', 'subscription', 'pets', 'gifts', 'personal_care', 'donations', 'shopping', 'travel', name='transactioncategory'), nullable=True),
    sa.Column('type', sa.Enum('proportional', 'even', 'individual', name='transactiontype'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_edited', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    # ### end Alembic commands ###
