"""add datetime fields to transaction

Revision ID: 9fdd9858c356
Revises: fc268cf07e66
Create Date: 2023-06-01 21:23:45.007115

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9fdd9858c356'
down_revision = 'fc268cf07e66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('transaction', sa.Column('last_edited', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'last_edited')
    op.drop_column('transaction', 'created_at')
    # ### end Alembic commands ###
